### ISSUE TITLE
Add D7 upgrade path

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/menu_pager#1]
The D7 version used block-specific variables (e.g. `variable_get('menu_pager_restrict_to_parent_' . $delta, FALSE)`). In Backdrop, block settings are saved automatically to each block's layout-specific config (e.g. `restrict_to_parent`). The question is, how do we convert the D7 variables to block settings for existing sites...?

**Comment by yorkshire-pudding** [comment]
This would be very complex to do (it is possible, but very long-winded) and there are only 32 D7 sites using this module at the time of writing (https://www.drupal.org/project/usage/menu_pager), and there is only one setting to apply per block.

If you wish to re-open and provide a PR, please feel free.
