### ISSUE TITLE
Fix 'Restrict to parent' setting?

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/menu_pager#3]
The 'Restrict to parent' setting makes it so that the next/previous links only show for links with the same parent (i.e. links at the same level of the hierarchy) as the current menu item. However I'm not convinced it's working as well as it should...

Take the following hierarchy:

![image](https://user-images.githubusercontent.com/2385329/113408994-19462080-93fc-11eb-9ee1-66b2cdc07116.png)

With the 'Restrict to parent' setting enabled, no links are displayed for the current page ('Installing'). This is because the menu hierarchy is flattened, the next and previous links obtained, then checked to see if they have the same parent as the current menu item. In this case, the previous link is 'Getting started' and it's one level up the hierarchy, so it's not shown. The next link is 'System requirements' and since it's one level down the hierarchy, then it's not shown either.

Yet my expectation was that a next link would be shown which pointed to 'Updating/upgrading' - i.e. the *next* link with the same parent. However, since this would require a re-write of how this feature currently works, and users might be used to it as-is, I'm not usre whether to change it or not...

**Comment by yorkshire-pudding** [comment]
@BWPanda - I agree with that expectation. That, to me, is a logical straightforward interpretation. I wouldn't worry about users being used to it as it is; there are no releases yet so I think you have to be deliberately looking for it on GitHub to know it is here.

**Comment by yorkshire-pudding** [comment]
There is an equivalent issue in the Drupal issue queue but only for the D8+ version - see https://www.drupal.org/project/menu_pager/issues/3357153

I've had a look at the [commit](https://git.drupalcode.org/project/menu_pager/-/merge_requests/5/diffs) but I don't think there is a simple comparable function in Backdrop that does the same thing.
