### ISSUE TITLE
Notice: Undefined index: menu_name in menu_pager_get_navigation() in dblog

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/menu_pager#4]
If the current path is not in any menu, then visiting the path puts multiple PHP errors into the dblog like this:

```
Notice: Undefined index: menu_name in menu_pager_get_navigation() (line 187 of /home/docs/repo/www/modules/contrib/menu_pager/menu_pager.module).
```

One can see many examples of this on https://docs.backdropcms.org. To reproduce:

* Visit any API page, e.g., https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_goto/1
* Visit the dblog, https://docs.backdropcms.org/admin/reports/dblog

The problem can be eliminated by adding the following to the beginning of functions `menu_pager_get_navigation()` and `menu_pager_get_children()`:

```
  if (!isset($menu_link['menu_name'])) {
    return array();
  }
```

**Comment by ghost** [comment]
Thanks @bugfolder. Care to make a PR to that effect?

**Comment by jenlampton** [comment]
PR applied to docs.backdropcms.org (to help debuging https://github.com/backdrop-ops/docs.backdropcms.org/issues/181)

**Comment by ghost** [comment]
Merged, thanks @bugfolder
